# Generated by Django 3.0.6 on 2020-06-29 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organizations',
            new_name='Organization',
        ),
    ]
