# Generated by Django 3.0.6 on 2020-06-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteerapp', '0002_auto_20200629_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='picture',
            field=models.ImageField(max_length=150, upload_to='images/'),
        ),
    ]
