# Generated by Django 3.0.6 on 2020-07-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteerapp', '0004_auto_20200630_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
