# Generated by Django 3.0.6 on 2020-07-02 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteerapp', '0005_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
